"""Reporting tasks — monthly reports, evidence and policy review reminders."""
import logging
import os
from datetime import datetime, timedelta
from celery_app import app, get_sync_session

logger = logging.getLogger(__name__)

# Where generated report PDFs are written. Override with REPORTS_DIR. Should be a
# Docker volume in production so reports survive container restarts.
REPORTS_DIR = os.getenv("REPORTS_DIR", "/app/data/reports")


def _render_report_pdf(path: str, firm_name: str, period: str,
                       alerts_count: int, scans_count: int) -> int:
    """Render a one-page compliance report PDF. Returns the file size in bytes."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4
    y = height - 30 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawString(20 * mm, y, "Seema — Monthly Compliance Report")
    y -= 12 * mm
    c.setFont("Helvetica", 12)
    c.drawString(20 * mm, y, f"Firm: {firm_name}")
    y -= 7 * mm
    c.drawString(20 * mm, y, f"Period: {period}")
    y -= 7 * mm
    c.drawString(20 * mm, y, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    y -= 14 * mm

    c.setFont("Helvetica-Bold", 13)
    c.drawString(20 * mm, y, "Summary")
    y -= 9 * mm
    c.setFont("Helvetica", 12)
    c.drawString(25 * mm, y, f"• Compliance alerts raised this month: {alerts_count}")
    y -= 7 * mm
    c.drawString(25 * mm, y, f"• Automated scan checks recorded: {scans_count}")
    y -= 14 * mm

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(20 * mm, 20 * mm,
                 "Auto-generated by Seema. Retain as part of your firm's SRA evidence pack.")
    c.showPage()
    c.save()
    return os.path.getsize(path)


@app.task(name="tasks.reporting_tasks.generate_monthly_compliance_report")
def generate_monthly_compliance_report():
    """Generate a monthly compliance report PDF for every active firm and file
    it in the firm's evidence locker."""
    from models.firm import Firm
    from models.compliance import ComplianceAlert, ComplianceScanResult
    from models.evidence import EvidenceDocument

    logger.info("Generating monthly compliance reports")
    session = get_sync_session()
    try:
        firms = session.query(Firm).filter(Firm.is_active == True).all()  # noqa: E712
        reports_generated = 0
        now = datetime.utcnow()
        month_start = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        period = month_start.strftime("%B %Y")

        os.makedirs(REPORTS_DIR, exist_ok=True)

        for firm in firms:
            alerts_count = session.query(ComplianceAlert).filter(
                ComplianceAlert.firm_id == firm.id,
                ComplianceAlert.created_at >= month_start,
            ).count()
            scans_count = session.query(ComplianceScanResult).filter(
                ComplianceScanResult.firm_id == firm.id,
                ComplianceScanResult.created_at >= month_start,
            ).count()

            filename = f"compliance_report_{firm.id}_{month_start.strftime('%Y%m')}.pdf"
            file_path = os.path.join(REPORTS_DIR, filename)

            try:
                file_size = _render_report_pdf(
                    file_path, firm.name, period, alerts_count, scans_count
                )
            except Exception as pdf_err:
                logger.error(f"PDF render failed for firm {firm.id}: {pdf_err}")
                continue

            session.add(EvidenceDocument(
                firm_id=firm.id,
                title=f"Monthly Compliance Report — {period}",
                description=(
                    f"Automated compliance report for {period}: "
                    f"{alerts_count} alerts, {scans_count} scan checks."
                ),
                category="compliance_report",
                file_path=file_path,
                file_size=file_size,
                status="reviewed",
            ))
            reports_generated += 1
            logger.info(f"Report filed for {firm.name}: {file_path}")

        session.commit()
        logger.info(f"Monthly reports generated: {reports_generated}")
        return {"reports_generated": reports_generated}
    except Exception as e:
        session.rollback()
        logger.error(f"Monthly report generation failed: {e}")
        raise
    finally:
        session.close()


@app.task(name="tasks.reporting_tasks.check_evidence_review_dates")
def check_evidence_review_dates():
    """Check for evidence documents due for review."""
    from models.evidence import EvidenceDocument
    from models.compliance import ComplianceTask

    logger.info("Checking evidence review dates")
    session = get_sync_session()
    try:
        upcoming = (datetime.utcnow() + timedelta(days=30)).strftime("%Y-%m-%d")
        documents = session.query(EvidenceDocument).filter(
            EvidenceDocument.next_review_date <= upcoming,
            EvidenceDocument.status == "active",
        ).all()
        tasks_created = 0
        for doc in documents:
            task = ComplianceTask(
                firm_id=doc.firm_id,
                task_type="evidence_review",
                title=f"Evidence review due: {doc.title}",
                description=f"Document '{doc.title}' is due for review by {doc.next_review_date}",
                priority="medium",
                due_date=doc.next_review_date,
            )
            session.add(task)
            tasks_created += 1
        session.commit()
        logger.info(f"Evidence review check: {tasks_created} tasks created")
        return {"documents_due": len(documents), "tasks_created": tasks_created}
    except Exception as e:
        session.rollback()
        logger.error(f"Evidence review check failed: {e}")
        raise
    finally:
        session.close()


@app.task(name="tasks.reporting_tasks.check_policy_review_dates")
def check_policy_review_dates():
    """Check for policy documents due for review."""
    from models.policies import PolicyDocument
    from models.compliance import ComplianceTask

    logger.info("Checking policy review dates")
    session = get_sync_session()
    try:
        upcoming = (datetime.utcnow() + timedelta(days=30)).strftime("%Y-%m-%d")
        policies = session.query(PolicyDocument).filter(
            PolicyDocument.next_review_date <= upcoming,
            PolicyDocument.status == "active",
        ).all()
        tasks_created = 0
        for policy in policies:
            task = ComplianceTask(
                firm_id=policy.firm_id,
                task_type="policy_review",
                title=f"Policy review due: {policy.title}",
                description=f"Policy '{policy.title}' is due for review by {policy.next_review_date}",
                priority="high",
                due_date=policy.next_review_date,
            )
            session.add(task)
            tasks_created += 1
        session.commit()
        logger.info(f"Policy review check: {tasks_created} tasks created")
        return {"policies_due": len(policies), "tasks_created": tasks_created}
    except Exception as e:
        session.rollback()
        logger.error(f"Policy review check failed: {e}")
        raise
    finally:
        session.close()
