import prisma from './prisma.js';
import { runWithFirm } from './tenantContext.js';

// ---------------------------------------------------------------------------
// packRenderer — server-side HTML rendering for the two compliance packs
// the platform can email to recipients.
//
// Why this lives here, not duplicated in the worker
// -------------------------------------------------
// The Node API and the BullMQ email worker BOTH need to render a pack:
// the API for any future "preview" route, the worker for the actual
// attachment we ship to brokers / SRA inspectors. Rather than copy the
// HTML template into both places, we centralise it here.
//
// We deliberately reuse the same data shape the existing routes already
// produce — `routes/piiRenewal.ts` for PII renewal, and the SRA audit
// snapshot the FastAPI service produces for SRA inspection. This file
// only owns the HTML SHELL; data assembly lives where it always lived.
// That keeps "don't reinvent the PDF generator" honest.
// ---------------------------------------------------------------------------

export interface RenderedPack {
  html: string;
  filename: string;
}

export async function renderPackHtml(firmId: string, packType: string): Promise<RenderedPack> {
  // The worker enters this function inside an AsyncLocalStorage scope set
  // by the dispatch wrapper, so RLS context is already correct. The
  // explicit runWithFirm here is a belt-and-braces guard for any caller
  // that forgets — Prisma will throw without it.
  return runWithFirm(firmId, async () => {
    if (packType === 'pii_renewal') {
      const html = await renderPiiRenewalPack(firmId);
      const stamp = new Date().toISOString().split('T')[0];
      return { html, filename: `pii-renewal-pack-${stamp}.html` };
    }
    if (packType === 'sra_audit') {
      const html = await renderSraAuditPack(firmId);
      const stamp = new Date().toISOString().split('T')[0];
      return { html, filename: `sra-inspection-pack-${stamp}.html` };
    }
    throw new Error(`Unknown packType '${packType}'`);
  });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function esc(s: unknown): string {
  if (s === null || s === undefined) return '—';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmtDate(iso: Date | string | null | undefined): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleDateString('en-GB');
  } catch {
    return '—';
  }
}

function shellWrap(title: string, firmName: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${esc(title)} — ${esc(firmName)}</title>
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #111; padding: 40px; max-width: 1000px; margin: 0 auto; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
    h2 { color: #1e40af; margin-top: 36px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
    h3 { color: #374151; margin-top: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13px; }
    th, td { border: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; }
    th { background: #f9fafb; font-weight: 600; text-transform: uppercase; font-size: 11px; color: #6b7280; }
    .meta { color: #6b7280; font-size: 12px; margin-bottom: 20px; }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-top: 12px; }
    .stat { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; }
    .stat .label { font-size: 11px; text-transform: uppercase; color: #6b7280; }
    .stat .value { font-size: 22px; font-weight: 700; margin-top: 4px; }
    .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 11px; }
  </style>
</head>
<body>
${body}
<div class="footer">Generated by Seema Compliance Platform on ${esc(new Date().toLocaleString('en-GB'))}.</div>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// PII Renewal Pack — mirrors the data assembled by
// routes/piiRenewal.ts → POST /compliance/pii-renewal-pack/generate.
// We re-query rather than HTTP-call ourselves so the worker doesn't need
// auth tokens. The query set is intentionally a strict subset of what the
// route returns — enough for an insurer to triage at renewal.
// ---------------------------------------------------------------------------
async function renderPiiRenewalPack(firmId: string): Promise<string> {
  const now = new Date();
  const twelveMonthsAgo = new Date(now.getTime() - 365 * 24 * 60 * 60 * 1000);

  const [
    firm,
    activeStaffCount,
    breachesLast12m,
    openBreachesCount,
    complaintsLast12m,
    cddTotal,
    cddCompleted,
    highRiskClients,
    sarsLast12m,
    policies,
    policiesOverdue,
  ] = await Promise.all([
    prisma.firm.findUnique({ where: { id: firmId } }),
    prisma.staffMember.count({ where: { firmId, status: 'active' } }),
    prisma.breachReport.findMany({
      where: { firmId, reportedDate: { gte: twelveMonthsAgo } },
      orderBy: { reportedDate: 'desc' },
      take: 25,
    }),
    prisma.breachReport.count({
      where: { firmId, OR: [{ status: 'open' }, { status: 'in_progress' }] },
    }),
    prisma.complaint.count({ where: { firmId, openedDate: { gte: twelveMonthsAgo } } }),
    prisma.cddRecord.count({ where: { firmId } }),
    prisma.cddRecord.count({
      where: { firmId, OR: [{ status: 'verified' }, { status: 'completed' }] },
    }),
    prisma.cddRecord.count({
      where: { firmId, OR: [{ riskLevel: 'high' }, { riskLevel: 'very_high' }] },
    }),
    prisma.sarRecord.count({ where: { firmId, reportDate: { gte: twelveMonthsAgo } } }),
    prisma.policyDocument.findMany({
      where: { firmId },
      select: { id: true, title: true, category: true, status: true, lastReviewed: true, nextReview: true },
      orderBy: { title: 'asc' },
      take: 50,
    }),
    prisma.policyDocument.count({ where: { firmId, nextReview: { lt: now } } }),
  ]);

  const cddPct = cddTotal > 0 ? Math.round((cddCompleted / cddTotal) * 100) : 0;

  const breachRows = breachesLast12m
    .map(
      (b) =>
        `<tr><td>${esc(b.title)}</td><td>${esc(b.severity)}</td><td>${esc(b.status)}</td><td>${esc(fmtDate(b.reportedDate))}</td></tr>`
    )
    .join('');

  const policyRows = policies
    .map(
      (p) =>
        `<tr><td>${esc(p.title)}</td><td>${esc(p.category)}</td><td>${esc(p.status)}</td><td>${esc(fmtDate(p.lastReviewed))}</td><td>${esc(fmtDate(p.nextReview))}</td></tr>`
    )
    .join('');

  const body = `
  <h1>PII Renewal Evidence Pack</h1>
  <p class="meta">Generated ${esc(fmtDate(now))} for <strong>${esc(firm?.name)}</strong> (SRA ${esc(firm?.sraNumber)})</p>

  <h2>Firm Profile</h2>
  <table>
    <tr><th>Address</th><td>${esc(firm?.address)}</td></tr>
    <tr><th>Firm size</th><td>${esc(firm?.firmSize)}</td></tr>
    <tr><th>COLP</th><td>${esc(firm?.colpName)}</td></tr>
    <tr><th>COFA</th><td>${esc(firm?.cofaName)}</td></tr>
    <tr><th>MLRO</th><td>${esc(firm?.mlroName)}</td></tr>
  </table>

  <h2>Staff &amp; Compliance Posture</h2>
  <div class="stats">
    <div class="stat"><div class="label">Active staff</div><div class="value">${activeStaffCount}</div></div>
    <div class="stat"><div class="label">CDD records</div><div class="value">${cddTotal}</div></div>
    <div class="stat"><div class="label">CDD completion</div><div class="value">${cddPct}%</div></div>
    <div class="stat"><div class="label">High-risk clients</div><div class="value">${highRiskClients}</div></div>
  </div>

  <h2>Breaches &amp; Claims (last 12 months)</h2>
  <div class="stats">
    <div class="stat"><div class="label">Total breaches</div><div class="value">${breachesLast12m.length}</div></div>
    <div class="stat"><div class="label">Open</div><div class="value">${openBreachesCount}</div></div>
    <div class="stat"><div class="label">Complaints</div><div class="value">${complaintsLast12m}</div></div>
    <div class="stat"><div class="label">SARs filed</div><div class="value">${sarsLast12m}</div></div>
  </div>
  ${breachRows ? `<table><thead><tr><th>Title</th><th>Severity</th><th>Status</th><th>Reported</th></tr></thead><tbody>${breachRows}</tbody></table>` : ''}

  <h2>Policy Library</h2>
  <div class="stats">
    <div class="stat"><div class="label">Policies</div><div class="value">${policies.length}</div></div>
    <div class="stat"><div class="label">Overdue for review</div><div class="value">${policiesOverdue}</div></div>
  </div>
  ${policyRows ? `<table><thead><tr><th>Title</th><th>Category</th><th>Status</th><th>Last reviewed</th><th>Next review</th></tr></thead><tbody>${policyRows}</tbody></table>` : ''}
  `;

  return shellWrap('PII Renewal Evidence Pack', firm?.name ?? 'Firm', body);
}

// ---------------------------------------------------------------------------
// SRA Inspection Pack — server-side counterpart of the HTML the UI builds
// in seema-web/src/app/sra-audit/page.tsx → buildPackHTML(). We assemble
// from the raw compliance scan results since the FastAPI snapshot endpoint
// requires a JWT and the worker has no caller token.
// ---------------------------------------------------------------------------
async function renderSraAuditPack(firmId: string): Promise<string> {
  const [firm, scanResults, openAlerts] = await Promise.all([
    prisma.firm.findUnique({ where: { id: firmId } }),
    prisma.complianceScanResult.findMany({
      where: { firmId },
      orderBy: { scanDate: 'desc' },
      take: 50,
    }),
    prisma.complianceAlert.findMany({
      where: { firmId, status: 'open' },
      orderBy: { createdAt: 'desc' },
      take: 25,
    }),
  ]);

  const passing = scanResults.filter((r) => /pass|complet|complian/i.test(r.status || '')).length;
  const failing = scanResults.filter((r) => /fail|non[_-]?complian/i.test(r.status || '')).length;
  const total = scanResults.length;
  const score = total > 0 ? Math.round((passing / total) * 100) : 0;

  const itemRows = scanResults
    .map(
      (r) =>
        `<tr><td>${esc(r.category)}</td><td>${esc(r.checkName)}</td><td>${esc(r.status)}</td><td>${esc(fmtDate(r.scanDate))}</td></tr>`
    )
    .join('');

  const alertRows = openAlerts
    .map(
      (a) =>
        `<tr><td>${esc(a.severity)}</td><td>${esc(a.title)}</td><td>${esc(a.alertType)}</td><td>${esc(fmtDate(a.createdAt))}</td></tr>`
    )
    .join('');

  const body = `
  <h1>SRA Inspection Pack</h1>
  <p class="meta">Generated ${esc(fmtDate(new Date()))} for <strong>${esc(firm?.name)}</strong> (SRA ${esc(firm?.sraNumber)})</p>

  <h2>Readiness Snapshot</h2>
  <div class="stats">
    <div class="stat"><div class="label">Readiness score</div><div class="value">${score}%</div></div>
    <div class="stat"><div class="label">Total checks</div><div class="value">${total}</div></div>
    <div class="stat"><div class="label">Passing</div><div class="value">${passing}</div></div>
    <div class="stat"><div class="label">Failing</div><div class="value">${failing}</div></div>
  </div>

  <h2>Compliance Checks</h2>
  ${itemRows ? `<table><thead><tr><th>Category</th><th>Check</th><th>Status</th><th>Last scan</th></tr></thead><tbody>${itemRows}</tbody></table>` : '<p>No scan results recorded.</p>'}

  <h2>Open Compliance Alerts</h2>
  ${alertRows ? `<table><thead><tr><th>Severity</th><th>Title</th><th>Type</th><th>Raised</th></tr></thead><tbody>${alertRows}</tbody></table>` : '<p>No open alerts — clean board.</p>'}

  <h2>Preparation Notes</h2>
  <ul>
    <li>Ensure all evidence files referenced above are readily accessible.</li>
    <li>COLP and COFA should review this pack and sign off before the visit.</li>
    <li>Client account reconciliation records should be available for the last 12 months.</li>
    <li>Staff training records and CPD logs should be up to date.</li>
    <li>AML risk assessment and related policies must be current.</li>
  </ul>
  `;

  return shellWrap('SRA Inspection Pack', firm?.name ?? 'Firm', body);
}
