"""initial schema

Revision ID: c52dd6e4eb76
Revises: 
Create Date: 2026-04-25 17:15:37.868791
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c52dd6e4eb76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sra_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('practice_areas', sa.Text(), nullable=True),
    sa.Column('firm_size', sa.Integer(), nullable=True),
    sa.Column('colp_name', sa.String(length=255), nullable=True),
    sa.Column('cofa_name', sa.String(length=255), nullable=True),
    sa.Column('mlro_name', sa.String(length=255), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sra_number')
    )
    op.create_table('industries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sra_feed_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feed_source', sa.String(length=100), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.Column('new_items', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.Column('period_start', sa.String(length=20), nullable=True),
    sa.Column('period_end', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_reports_firm_id'), 'audit_reports', ['firm_id'], unique=False)
    op.create_table('audit_trail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_firm_id'), 'audit_trail', ['firm_id'], unique=False)
    op.create_table('breach_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('breach_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('discovered_by', sa.String(length=36), nullable=True),
    sa.Column('affected_data', sa.Text(), nullable=True),
    sa.Column('affected_individuals', sa.Integer(), nullable=True),
    sa.Column('ico_notifiable', sa.Boolean(), nullable=True),
    sa.Column('ico_notified_at', sa.DateTime(), nullable=True),
    sa.Column('ico_reference', sa.String(length=100), nullable=True),
    sa.Column('individuals_notified_at', sa.DateTime(), nullable=True),
    sa.Column('containment_actions', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remedial_actions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_72h', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_reports_firm_id'), 'breach_reports', ['firm_id'], unique=False)
    op.create_table('client_intake',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('cdd_status', sa.String(length=20), nullable=True),
    sa.Column('edd_required', sa.Boolean(), nullable=True),
    sa.Column('pep_flag', sa.Boolean(), nullable=True),
    sa.Column('jurisdiction_risk', sa.String(length=20), nullable=True),
    sa.Column('source_of_funds', sa.Text(), nullable=True),
    sa.Column('source_of_wealth', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=36), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_intake_firm_id'), 'client_intake', ['firm_id'], unique=False)
    op.create_table('compliance_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_alerts_firm_id'), 'compliance_alerts', ['firm_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=True),
    sa.Column('check_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_firm_id'), 'compliance_checks', ['firm_id'], unique=False)
    op.create_table('compliance_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_tasks_firm_id'), 'compliance_tasks', ['firm_id'], unique=False)
    op.create_table('email_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('to_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_queue_firm_id'), 'email_queue', ['firm_id'], unique=False)
    op.create_table('email_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_chase_training', sa.Boolean(), nullable=True),
    sa.Column('auto_chase_reviews', sa.Boolean(), nullable=True),
    sa.Column('auto_chase_cdd', sa.Boolean(), nullable=True),
    sa.Column('chase_frequency_days', sa.Integer(), nullable=True),
    sa.Column('escalation_after_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id')
    )
    op.create_table('evidence_locker',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_ref', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_locker_firm_id'), 'evidence_locker', ['firm_id'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('imported_by', sa.String(length=36), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_firm_id'), 'import_logs', ['firm_id'], unique=False)
    op.create_table('law_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_clients_firm_id'), 'law_clients', ['firm_id'], unique=False)
    op.create_table('matter_checklists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('case_name', sa.String(length=255), nullable=True),
    sa.Column('matter_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('completed_items', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_checklists_firm_id'), 'matter_checklists', ['firm_id'], unique=False)
    op.create_table('policy_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('policy_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_firm_id'), 'policy_documents', ['firm_id'], unique=False)
    op.create_table('regulatory_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('published_date', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_updates_firm_id'), 'regulatory_updates', ['firm_id'], unique=False)
    op.create_table('remediation_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_plans_firm_id'), 'remediation_plans', ['firm_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('sra_score', sa.Integer(), nullable=True),
    sa.Column('aml_score', sa.Integer(), nullable=True),
    sa.Column('cpr_score', sa.Integer(), nullable=True),
    sa.Column('gdpr_score', sa.Integer(), nullable=True),
    sa.Column('limitation_score', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_firm_id'), 'risk_scores', ['firm_id'], unique=False)
    op.create_table('sra_audit_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('evidence_ref', sa.String(length=36), nullable=True),
    sa.Column('last_reviewed', sa.String(length=30), nullable=True),
    sa.Column('next_review_due', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sra_audit_items_firm_id'), 'sra_audit_items', ['firm_id'], unique=False)
    op.create_table('staff_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pqe', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_members_firm_id'), 'staff_members', ['firm_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=True),
    sa.Column('industry_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_firm_id'), 'workflows', ['firm_id'], unique=False)
    op.create_table('breach_report_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('breach_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['breach_id'], ['breach_reports.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_report_steps_breach_id'), 'breach_report_steps', ['breach_id'], unique=False)
    op.create_index(op.f('ix_breach_report_steps_firm_id'), 'breach_report_steps', ['firm_id'], unique=False)
    op.create_table('chaser_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('chaser_type', sa.String(length=50), nullable=True),
    sa.Column('recipient_staff_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['recipient_staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chaser_log_firm_id'), 'chaser_log', ['firm_id'], unique=False)
    op.create_table('law_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('case_name', sa.String(length=255), nullable=True),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('opened_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['law_clients.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_cases_client_id'), 'law_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_law_cases_firm_id'), 'law_cases', ['firm_id'], unique=False)
    op.create_table('matter_checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['matter_checklists.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_checklist_items_checklist_id'), 'matter_checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_matter_checklist_items_firm_id'), 'matter_checklist_items', ['firm_id'], unique=False)
    op.create_table('policy_update_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('policy_type', sa.String(length=100), nullable=True),
    sa.Column('trigger_update_id', sa.String(length=36), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('suggested_changes', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_update_queue_firm_id'), 'policy_update_queue', ['firm_id'], unique=False)
    op.create_table('regulatory_impact_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('update_id', sa.String(length=36), nullable=True),
    sa.Column('affected_areas', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('affected_policies', sa.Text(), nullable=True),
    sa.Column('affected_staff_roles', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['regulatory_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_impact_analysis_firm_id'), 'regulatory_impact_analysis', ['firm_id'], unique=False)
    op.create_index(op.f('ix_regulatory_impact_analysis_update_id'), 'regulatory_impact_analysis', ['update_id'], unique=False)
    op.create_table('remediation_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('regulation_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['remediation_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_steps_firm_id'), 'remediation_steps', ['firm_id'], unique=False)
    op.create_index(op.f('ix_remediation_steps_plan_id'), 'remediation_steps', ['plan_id'], unique=False)
    op.create_table('staff_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_actions_firm_id'), 'staff_actions', ['firm_id'], unique=False)
    op.create_index(op.f('ix_staff_actions_staff_id'), 'staff_actions', ['staff_id'], unique=False)
    op.create_table('staff_file_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_file_reviews_firm_id'), 'staff_file_reviews', ['firm_id'], unique=False)
    op.create_index(op.f('ix_staff_file_reviews_staff_id'), 'staff_file_reviews', ['staff_id'], unique=False)
    op.create_table('staff_training',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('training_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('cpd_hours', sa.Float(), nullable=True),
    sa.Column('certificate_ref', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_training_firm_id'), 'staff_training', ['firm_id'], unique=False)
    op.create_index(op.f('ix_staff_training_staff_id'), 'staff_training', ['staff_id'], unique=False)
    op.create_table('supervision_schedule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('next_due', sa.String(length=20), nullable=True),
    sa.Column('last_completed', sa.String(length=30), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_schedule_firm_id'), 'supervision_schedule', ['firm_id'], unique=False)
    op.create_index(op.f('ix_supervision_schedule_staff_id'), 'supervision_schedule', ['staff_id'], unique=False)
    op.create_table('user_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_accounts_firm_id'), 'user_accounts', ['firm_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('data_input', sa.Text(), nullable=True),
    sa.Column('data_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_firm_id'), 'workflow_runs', ['firm_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('law_communications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sent_date', sa.String(length=30), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['law_cases.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_communications_case_id'), 'law_communications', ['case_id'], unique=False)
    op.create_index(op.f('ix_law_communications_firm_id'), 'law_communications', ['firm_id'], unique=False)
    op.create_table('law_deadlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('deadline_type', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cpr_rule', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['law_cases.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_deadlines_case_id'), 'law_deadlines', ['case_id'], unique=False)
    op.create_index(op.f('ix_law_deadlines_firm_id'), 'law_deadlines', ['firm_id'], unique=False)
    op.create_table('law_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['law_cases.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_documents_case_id'), 'law_documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_law_documents_firm_id'), 'law_documents', ['firm_id'], unique=False)
    op.create_table('law_time_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('attorney_id', sa.String(length=36), nullable=True),
    sa.Column('attorney_name', sa.String(length=255), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['law_cases.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_time_entries_case_id'), 'law_time_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_law_time_entries_firm_id'), 'law_time_entries', ['firm_id'], unique=False)
    op.create_table('run_step_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_step_logs_run_id'), 'run_step_logs', ['run_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_user_sessions_firm_id'), 'user_sessions', ['firm_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_firm_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_run_step_logs_run_id'), table_name='run_step_logs')
    op.drop_table('run_step_logs')
    op.drop_index(op.f('ix_law_time_entries_firm_id'), table_name='law_time_entries')
    op.drop_index(op.f('ix_law_time_entries_case_id'), table_name='law_time_entries')
    op.drop_table('law_time_entries')
    op.drop_index(op.f('ix_law_documents_firm_id'), table_name='law_documents')
    op.drop_index(op.f('ix_law_documents_case_id'), table_name='law_documents')
    op.drop_table('law_documents')
    op.drop_index(op.f('ix_law_deadlines_firm_id'), table_name='law_deadlines')
    op.drop_index(op.f('ix_law_deadlines_case_id'), table_name='law_deadlines')
    op.drop_table('law_deadlines')
    op.drop_index(op.f('ix_law_communications_firm_id'), table_name='law_communications')
    op.drop_index(op.f('ix_law_communications_case_id'), table_name='law_communications')
    op.drop_table('law_communications')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_firm_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_user_accounts_firm_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_supervision_schedule_staff_id'), table_name='supervision_schedule')
    op.drop_index(op.f('ix_supervision_schedule_firm_id'), table_name='supervision_schedule')
    op.drop_table('supervision_schedule')
    op.drop_index(op.f('ix_staff_training_staff_id'), table_name='staff_training')
    op.drop_index(op.f('ix_staff_training_firm_id'), table_name='staff_training')
    op.drop_table('staff_training')
    op.drop_index(op.f('ix_staff_file_reviews_staff_id'), table_name='staff_file_reviews')
    op.drop_index(op.f('ix_staff_file_reviews_firm_id'), table_name='staff_file_reviews')
    op.drop_table('staff_file_reviews')
    op.drop_index(op.f('ix_staff_actions_staff_id'), table_name='staff_actions')
    op.drop_index(op.f('ix_staff_actions_firm_id'), table_name='staff_actions')
    op.drop_table('staff_actions')
    op.drop_index(op.f('ix_remediation_steps_plan_id'), table_name='remediation_steps')
    op.drop_index(op.f('ix_remediation_steps_firm_id'), table_name='remediation_steps')
    op.drop_table('remediation_steps')
    op.drop_index(op.f('ix_regulatory_impact_analysis_update_id'), table_name='regulatory_impact_analysis')
    op.drop_index(op.f('ix_regulatory_impact_analysis_firm_id'), table_name='regulatory_impact_analysis')
    op.drop_table('regulatory_impact_analysis')
    op.drop_index(op.f('ix_policy_update_queue_firm_id'), table_name='policy_update_queue')
    op.drop_table('policy_update_queue')
    op.drop_index(op.f('ix_matter_checklist_items_firm_id'), table_name='matter_checklist_items')
    op.drop_index(op.f('ix_matter_checklist_items_checklist_id'), table_name='matter_checklist_items')
    op.drop_table('matter_checklist_items')
    op.drop_index(op.f('ix_law_cases_firm_id'), table_name='law_cases')
    op.drop_index(op.f('ix_law_cases_client_id'), table_name='law_cases')
    op.drop_table('law_cases')
    op.drop_index(op.f('ix_chaser_log_firm_id'), table_name='chaser_log')
    op.drop_table('chaser_log')
    op.drop_index(op.f('ix_breach_report_steps_firm_id'), table_name='breach_report_steps')
    op.drop_index(op.f('ix_breach_report_steps_breach_id'), table_name='breach_report_steps')
    op.drop_table('breach_report_steps')
    op.drop_index(op.f('ix_workflows_firm_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_staff_members_firm_id'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_sra_audit_items_firm_id'), table_name='sra_audit_items')
    op.drop_table('sra_audit_items')
    op.drop_index(op.f('ix_risk_scores_firm_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_remediation_plans_firm_id'), table_name='remediation_plans')
    op.drop_table('remediation_plans')
    op.drop_index(op.f('ix_regulatory_updates_firm_id'), table_name='regulatory_updates')
    op.drop_table('regulatory_updates')
    op.drop_index(op.f('ix_policy_documents_firm_id'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_matter_checklists_firm_id'), table_name='matter_checklists')
    op.drop_table('matter_checklists')
    op.drop_index(op.f('ix_law_clients_firm_id'), table_name='law_clients')
    op.drop_table('law_clients')
    op.drop_index(op.f('ix_import_logs_firm_id'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_evidence_locker_firm_id'), table_name='evidence_locker')
    op.drop_table('evidence_locker')
    op.drop_table('email_settings')
    op.drop_index(op.f('ix_email_queue_firm_id'), table_name='email_queue')
    op.drop_table('email_queue')
    op.drop_index(op.f('ix_compliance_tasks_firm_id'), table_name='compliance_tasks')
    op.drop_table('compliance_tasks')
    op.drop_index(op.f('ix_compliance_checks_firm_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_compliance_alerts_firm_id'), table_name='compliance_alerts')
    op.drop_table('compliance_alerts')
    op.drop_index(op.f('ix_client_intake_firm_id'), table_name='client_intake')
    op.drop_table('client_intake')
    op.drop_index(op.f('ix_breach_reports_firm_id'), table_name='breach_reports')
    op.drop_table('breach_reports')
    op.drop_index(op.f('ix_audit_trail_firm_id'), table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_audit_reports_firm_id'), table_name='audit_reports')
    op.drop_table('audit_reports')
    op.drop_table('sra_feed_log')
    op.drop_table('industries')
    op.drop_table('firms')
    # ### end Alembic commands ###
